export const TERRAIN_COLOR_MAP = {
  desert: "yellow-6",
  grasslands: "light-green-6",
  grass: "light-green-6",
  mountains: "blue-grey-6",
  jungle: "green-10",
  jungles: "green-10",
  rainforests: "light-green-10",
  tundra: "cyan-8",
  "ice caves": "cyan-4",
  "mountain ranges": "blue-grey-9",
  swamp: "lime-10",
  bogs: "lime-10",
  lakes: "light-blue-6",
  "grassy hills": "green-5",
  urban: "purple-8",
  cityscape: "purple-8",
  seas: "blue-10",
  ocean: "blue-10",
  oceans: "blue-10",
  rock: "blue-grey-4",
  scrublands: "brown-4",
  savanna: "orange-3",
  volcanoes: "red-7",
  rivers: "light-blue-4",
  glaciers: "indigo-5",
  fields: "yellow-3",
};
